language : node_js
node_js :
 - 10.15.0
install:
 - npm install
script:
 - npm run build:widgets
 - npm run build
 - npm run test -- --watch=false

 # Send coverage data to Coveralls
 after_script: npm run coverage